---
switchboard: 
  version: 1.0.1
  homeable: false
  required: true
  description: Switchboard is a general service package for managing message routing in the system.
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html
  tables: 
    switchboard_prefs: |
      
      package C(128) NOTNULL,
      event_type C(128) NOTNULL,
      user_id I4 NOTNULL,
      content_id I4,
      delivery_style C(64) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `switchboard_prefs_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `switchboard_prfs_user_ref` FOREIGN KEY (`user_id`) REFERENCES `users_users` (`user_id`) '
      
    switchboard_queue: |
      
      message_id I4 PRIMARY,
      package C(128) NOTNULL,
      event_type C(128) NOTNULL,
      content_id I4,
      sending_user_id I4,
      queue_date I8 NOTNULL,
      complete_date I8,
	  subject X,
      message X,
      alt_message X
      CONSTRAINT '
      , CONSTRAINT `switchboard_queue_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `switchboard_queue_user_ref` FOREIGN KEY (`sending_user_id`) REFERENCES `users_users` (`user_id`) '
      
    switchboard_recipients: |
      
      message_id I4 PRIMARY,
      user_id I4 PRIMARY,
      delivery_style C(64) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `switchboard_recipients_m_ref` FOREIGN KEY (`message_id`) REFERENCES `switchboard_queue` (`message_id`)
      , CONSTRAINT `switchboard_recipients_usr_ref` FOREIGN KEY (`user_id`) REFERENCES `users_users` (`user_id`) '
      
  sequences: 
    switchboard_queue_id_seq: 
      start: 1
  indexes: 
    switchboard_prefs_pkg_idx: 
      table: switchboard_prefs
      cols: package
      opts: 
    switchboard_prefs_type_idx: 
      table: switchboard_prefs
      cols: event_type
      opts: 
    switchboard_prefs_user_idx: 
      table: switchboard_prefs
      cols: user_id
      opts: 
    switchboard_prefs_content_idx: 
      table: switchboard_prefs
      cols: content_id
      opts: 
  preferences: 
    switchboard_default_transport: email
  plugins:
    switchboard:
      handler_file: SwitchboardSystem.php
      required: true
      api_handlers:
        tpl:
          content_icon_tpl: 'bitpackage:switchboard/service_content_icon_inc.tpl',
        function:
          users_expunge: switchboard_user_expunge
          content_expunge: switchboard_content_expunge
